### ISSUE TITLE
ReadMe Guide missing something or not compiling.  bash: pip: command not found

### ISSUE THREAD

**Issue by smarthomesydney** [jac459/NeeoDriversInBrain#2]
[root@NEEO-xxxxxx neeo]# sudo pacman -S python-pip
resolving dependencies...

looking for conflicting packages...

Packages (36) bzip2-1.0.8-3  e2fsprogs-1.45.6-2  expat-2.2.9-3
              keyutils-1.6.3-1  krb5-1.18.2-1  libldap-2.4.50-2  libnsl-1.2.0-2
              libsasl-2.1.27-3  libtirpc-1.2.6-1  libutil-linux-2.36-1
              python-3.8.5-1  python-appdirs-1.4.4-1
              python-cachecontrol-0.12.6-1  python-chardet-3.0.4-5
              python-colorama-0.4.3-1  python-contextlib2-0.6.0.post1-1
              python-distlib-0.3.1-1  python-distro-1.5.0-1
              python-html5lib-1.1-1  python-idna-2.10-1  python-msgpack-1.0.0-1
              python-ordered-set-4.0.2-1  python-packaging-20.4-1
              python-pep517-0.8.2-1  python-progress-1.5-3
              python-pyparsing-2.4.7-1  python-requests-2.24.0-1
              python-resolvelib-0.4.0-1  python-retrying-1.3.3-7
              python-setuptools-1:49.2.1-1  python-six-1.15.0-1
              python-toml-0.10.1-1  python-urllib3-1.25.10-1
              python-webencodings-0.5.1-4  zlib-1:1.2.11-4  python-pip-20.1.1-1

Total Installed Size:  73.44 MiB

:: Proceed with installation? [Y/n] Y
(36/36) checking keys in keyring                   [######################] 100%
(36/36) checking package integrity                 [######################] 100%
(36/36) loading package files                      [######################] 100%
(36/36) checking for file conflicts                [######################] 100%
error: failed to commit transaction (conflicting files)
expat: /usr/bin/xmlwf exists in filesystem
expat: /usr/lib/libexpat.so exists in filesystem
expat: /usr/lib/libexpat.so.1 exists in filesystem
expat: /usr/lib/pkgconfig/expat.pc exists in filesystem
expat: /usr/share/licenses/expat/COPYING exists in filesystem
bzip2: /usr/bin/bunzip2 exists in filesystem
bzip2: /usr/bin/bzcat exists in filesystem
bzip2: /usr/bin/bzdiff exists in filesystem
bzip2: /usr/bin/bzgrep exists in filesystem
bzip2: /usr/bin/bzip2 exists in filesystem
bzip2: /usr/bin/bzip2recover exists in filesystem
bzip2: /usr/bin/bzmore exists in filesystem
bzip2: /usr/lib/libbz2.so exists in filesystem
bzip2: /usr/lib/libbz2.so.1 exists in filesystem
bzip2: /usr/lib/libbz2.so.1.0 exists in filesystem
bzip2: /usr/share/licenses/bzip2/LICENSE exists in filesystem
zlib: /usr/lib/libz.a exists in filesystem
zlib: /usr/lib/libz.so exists in filesystem
zlib: /usr/lib/libz.so.1 exists in filesystem
zlib: /usr/lib/libz.so.1.2.11 exists in filesystem
zlib: /usr/lib/pkgconfig/zlib.pc exists in filesystem
zlib: /usr/share/licenses/zlib/LICENSE exists in filesystem
libutil-linux: /usr/lib/libblkid.so exists in filesystem
libutil-linux: /usr/lib/libblkid.so.1 exists in filesystem
libutil-linux: /usr/lib/libblkid.so.1.1.0 exists in filesystem
libutil-linux: /usr/lib/libfdisk.so exists in filesystem
libutil-linux: /usr/lib/libfdisk.so.1 exists in filesystem
libutil-linux: /usr/lib/libfdisk.so.1.1.0 exists in filesystem
libutil-linux: /usr/lib/libmount.so exists in filesystem
libutil-linux: /usr/lib/libmount.so.1 exists in filesystem
libutil-linux: /usr/lib/libmount.so.1.1.0 exists in filesystem
libutil-linux: /usr/lib/libsmartcols.so exists in filesystem
libutil-linux: /usr/lib/libsmartcols.so.1 exists in filesystem
libutil-linux: /usr/lib/libsmartcols.so.1.1.0 exists in filesystem
libutil-linux: /usr/lib/libuuid.so exists in filesystem
libutil-linux: /usr/lib/libuuid.so.1 exists in filesystem
libutil-linux: /usr/lib/libuuid.so.1.3.0 exists in filesystem
e2fsprogs: /usr/bin/badblocks exists in filesystem
e2fsprogs: /usr/bin/chattr exists in filesystem
e2fsprogs: /usr/bin/compile_et exists in filesystem
e2fsprogs: /usr/bin/debugfs exists in filesystem
e2fsprogs: /usr/bin/dumpe2fs exists in filesystem
e2fsprogs: /usr/bin/e2freefrag exists in filesystem
e2fsprogs: /usr/bin/e2fsck exists in filesystem
e2fsprogs: /usr/bin/e2image exists in filesystem
e2fsprogs: /usr/bin/e2label exists in filesystem
e2fsprogs: /usr/bin/e2undo exists in filesystem
e2fsprogs: /usr/bin/e4crypt exists in filesystem
e2fsprogs: /usr/bin/e4defrag exists in filesystem
e2fsprogs: /usr/bin/filefrag exists in filesystem
e2fsprogs: /usr/bin/fsck.ext2 exists in filesystem
e2fsprogs: /usr/bin/fsck.ext3 exists in filesystem
e2fsprogs: /usr/bin/fsck.ext4 exists in filesystem
e2fsprogs: /usr/bin/logsave exists in filesystem
e2fsprogs: /usr/bin/lsattr exists in filesystem
e2fsprogs: /usr/bin/mk_cmds exists in filesystem
e2fsprogs: /usr/bin/mke2fs exists in filesystem
e2fsprogs: /usr/bin/mkfs.ext2 exists in filesystem
e2fsprogs: /usr/bin/mkfs.ext3 exists in filesystem
e2fsprogs: /usr/bin/mkfs.ext4 exists in filesystem
e2fsprogs: /usr/bin/mklost+found exists in filesystem
e2fsprogs: /usr/bin/resize2fs exists in filesystem
e2fsprogs: /usr/bin/tune2fs exists in filesystem
e2fsprogs: /usr/lib/e2initrd_helper exists in filesystem
e2fsprogs: /usr/lib/libcom_err.so exists in filesystem
e2fsprogs: /usr/lib/libcom_err.so.2 exists in filesystem
e2fsprogs: /usr/lib/libcom_err.so.2.1 exists in filesystem
e2fsprogs: /usr/lib/libe2p.so exists in filesystem
e2fsprogs: /usr/lib/libe2p.so.2 exists in filesystem
e2fsprogs: /usr/lib/libe2p.so.2.3 exists in filesystem
e2fsprogs: /usr/lib/libext2fs.so exists in filesystem
e2fsprogs: /usr/lib/libext2fs.so.2 exists in filesystem
e2fsprogs: /usr/lib/libext2fs.so.2.4 exists in filesystem
e2fsprogs: /usr/lib/libss.so exists in filesystem
e2fsprogs: /usr/lib/libss.so.2 exists in filesystem
e2fsprogs: /usr/lib/libss.so.2.0 exists in filesystem
e2fsprogs: /usr/lib/pkgconfig/com_err.pc exists in filesystem
e2fsprogs: /usr/lib/pkgconfig/e2p.pc exists in filesystem
e2fsprogs: /usr/lib/pkgconfig/ext2fs.pc exists in filesystem
e2fsprogs: /usr/lib/pkgconfig/ss.pc exists in filesystem
e2fsprogs: /usr/share/et/et_c.awk exists in filesystem
e2fsprogs: /usr/share/et/et_h.awk exists in filesystem
e2fsprogs: /usr/share/licenses/e2fsprogs/MIT-LICENSE exists in filesystem
e2fsprogs: /usr/share/ss/ct_c.awk exists in filesystem
e2fsprogs: /usr/share/ss/ct_c.sed exists in filesystem
libsasl: /usr/bin/pluginviewer exists in filesystem
libsasl: /usr/bin/sasldblistusers2 exists in filesystem
libsasl: /usr/bin/saslpasswd2 exists in filesystem
libsasl: /usr/lib/libsasl2.so exists in filesystem
libsasl: /usr/lib/libsasl2.so.3 exists in filesystem
libsasl: /usr/lib/libsasl2.so.3.0.0 exists in filesystem
libsasl: /usr/lib/pkgconfig/libsasl2.pc exists in filesystem
libsasl: /usr/lib/sasl2/libanonymous.so exists in filesystem
libsasl: /usr/lib/sasl2/libanonymous.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libanonymous.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/libcrammd5.so exists in filesystem
libsasl: /usr/lib/sasl2/libcrammd5.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libcrammd5.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/libdigestmd5.so exists in filesystem
libsasl: /usr/lib/sasl2/libdigestmd5.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libdigestmd5.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/liblogin.so exists in filesystem
libsasl: /usr/lib/sasl2/liblogin.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/liblogin.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/libntlm.so exists in filesystem
libsasl: /usr/lib/sasl2/libntlm.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libntlm.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/libplain.so exists in filesystem
libsasl: /usr/lib/sasl2/libplain.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libplain.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/libsasldb.so exists in filesystem
libsasl: /usr/lib/sasl2/libsasldb.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libsasldb.so.3.0.0 exists in filesystem
libsasl: /usr/lib/sasl2/libscram.so exists in filesystem
libsasl: /usr/lib/sasl2/libscram.so.3 exists in filesystem
libsasl: /usr/lib/sasl2/libscram.so.3.0.0 exists in filesystem
libsasl: /usr/share/licenses/libsasl/COPYING exists in filesystem
libldap: /usr/lib/liblber-2.4.so.2 exists in filesystem
libldap: /usr/lib/liblber.so exists in filesystem
libldap: /usr/lib/liblber.so.2 exists in filesystem
libldap: /usr/lib/libldap-2.4.so.2 exists in filesystem
libldap: /usr/lib/libldap.so exists in filesystem
libldap: /usr/lib/libldap.so.2 exists in filesystem
libldap: /usr/lib/libldap_r-2.4.so.2 exists in filesystem
libldap: /usr/lib/libldap_r.so exists in filesystem
libldap: /usr/share/licenses/libldap/LICENSE exists in filesystem
keyutils: /usr/bin/key.dns_resolver exists in filesystem
keyutils: /usr/bin/keyctl exists in filesystem
keyutils: /usr/bin/request-key exists in filesystem
keyutils: /usr/lib/libkeyutils.so exists in filesystem
keyutils: /usr/lib/libkeyutils.so.1 exists in filesystem
keyutils: /usr/share/keyutils/request-key-debug.sh exists in filesystem
krb5: /usr/bin/gss-client exists in filesystem
krb5: /usr/bin/gss-server exists in filesystem
krb5: /usr/bin/k5srvutil exists in filesystem
krb5: /usr/bin/kadmin exists in filesystem
krb5: /usr/bin/kadmin.local exists in filesystem
krb5: /usr/bin/kadmind exists in filesystem
krb5: /usr/bin/kdb5_ldap_util exists in filesystem
krb5: /usr/bin/kdb5_util exists in filesystem
krb5: /usr/bin/kdestroy exists in filesystem
krb5: /usr/bin/kinit exists in filesystem
krb5: /usr/bin/klist exists in filesystem
krb5: /usr/bin/kpasswd exists in filesystem
krb5: /usr/bin/kprop exists in filesystem
krb5: /usr/bin/kpropd exists in filesystem
krb5: /usr/bin/kproplog exists in filesystem
krb5: /usr/bin/krb5-config exists in filesystem
krb5: /usr/bin/krb5-send-pr exists in filesystem
krb5: /usr/bin/krb5kdc exists in filesystem
krb5: /usr/bin/ksu exists in filesystem
krb5: /usr/bin/kswitch exists in filesystem
krb5: /usr/bin/ktutil exists in filesystem
krb5: /usr/bin/kvno exists in filesystem
krb5: /usr/bin/sclient exists in filesystem
krb5: /usr/bin/sim_client exists in filesystem
krb5: /usr/bin/sim_server exists in filesystem
krb5: /usr/bin/sserver exists in filesystem
krb5: /usr/bin/uuclient exists in filesystem
krb5: /usr/bin/uuserver exists in filesystem
krb5: /usr/lib/krb5/plugins/kdb/db2.so exists in filesystem
krb5: /usr/lib/krb5/plugins/kdb/kldap.so exists in filesystem
krb5: /usr/lib/krb5/plugins/preauth/otp.so exists in filesystem
krb5: /usr/lib/krb5/plugins/preauth/pkinit.so exists in filesystem
krb5: /usr/lib/krb5/plugins/preauth/test.so exists in filesystem
krb5: /usr/lib/krb5/plugins/tls/k5tls.so exists in filesystem
krb5: /usr/lib/libgssapi_krb5.so exists in filesystem
krb5: /usr/lib/libgssapi_krb5.so.2 exists in filesystem
krb5: /usr/lib/libgssapi_krb5.so.2.2 exists in filesystem
krb5: /usr/lib/libgssrpc.so exists in filesystem
krb5: /usr/lib/libgssrpc.so.4 exists in filesystem
krb5: /usr/lib/libgssrpc.so.4.2 exists in filesystem
krb5: /usr/lib/libk5crypto.so exists in filesystem
krb5: /usr/lib/libk5crypto.so.3 exists in filesystem
krb5: /usr/lib/libk5crypto.so.3.1 exists in filesystem
krb5: /usr/lib/libkadm5clnt.so exists in filesystem
krb5: /usr/lib/libkadm5clnt_mit.so exists in filesystem
krb5: /usr/lib/libkadm5srv.so exists in filesystem
krb5: /usr/lib/libkadm5srv_mit.so exists in filesystem
krb5: /usr/lib/libkdb5.so exists in filesystem
krb5: /usr/lib/libkdb_ldap.so exists in filesystem
krb5: /usr/lib/libkdb_ldap.so.1 exists in filesystem
krb5: /usr/lib/libkdb_ldap.so.1.0 exists in filesystem
krb5: /usr/lib/libkrad.so exists in filesystem
krb5: /usr/lib/libkrad.so.0 exists in filesystem
krb5: /usr/lib/libkrad.so.0.0 exists in filesystem
krb5: /usr/lib/libkrb5.so exists in filesystem
krb5: /usr/lib/libkrb5.so.3 exists in filesystem
krb5: /usr/lib/libkrb5.so.3.3 exists in filesystem
krb5: /usr/lib/libkrb5support.so exists in filesystem
krb5: /usr/lib/libkrb5support.so.0 exists in filesystem
krb5: /usr/lib/libkrb5support.so.0.1 exists in filesystem
krb5: /usr/lib/libverto.so exists in filesystem
krb5: /usr/lib/libverto.so.0 exists in filesystem
krb5: /usr/lib/libverto.so.0.0 exists in filesystem
krb5: /usr/lib/pkgconfig/gssrpc.pc exists in filesystem
krb5: /usr/lib/pkgconfig/kadm-client.pc exists in filesystem
krb5: /usr/lib/pkgconfig/kadm-server.pc exists in filesystem
krb5: /usr/lib/pkgconfig/kdb.pc exists in filesystem
krb5: /usr/lib/pkgconfig/krb5-gssapi.pc exists in filesystem
krb5: /usr/lib/pkgconfig/krb5.pc exists in filesystem
krb5: /usr/lib/pkgconfig/mit-krb5-gssapi.pc exists in filesystem
krb5: /usr/lib/pkgconfig/mit-krb5.pc exists in filesystem
krb5: /usr/lib/systemd/system/krb5-kadmind.service exists in filesystem
krb5: /usr/lib/systemd/system/krb5-kdc.service exists in filesystem
krb5: /usr/lib/systemd/system/krb5-kpropd.service exists in filesystem
krb5: /usr/lib/systemd/system/krb5-kpropd.socket exists in filesystem
krb5: /usr/lib/systemd/system/krb5-kpropd@.service exists in filesystem
krb5: /usr/share/aclocal/ac_check_krb5.m4 exists in filesystem
krb5: /usr/share/licenses/krb5/LICENSE exists in filesystem
krb5: /usr/share/locale/en_US/LC_MESSAGES/mit-krb5.mo exists in filesystem
libtirpc: /usr/lib/libtirpc.so exists in filesystem
libtirpc: /usr/lib/libtirpc.so.3 exists in filesystem
libtirpc: /usr/lib/libtirpc.so.3.0.0 exists in filesystem
libtirpc: /usr/lib/pkgconfig/libtirpc.pc exists in filesystem
libtirpc: /usr/share/licenses/libtirpc/LICENSE exists in filesystem
libnsl: /usr/lib/libnsl.so exists in filesystem
libnsl: /usr/lib/libnsl.so.2 exists in filesystem
libnsl: /usr/lib/libnsl.so.2.0.0 exists in filesystem
libnsl: /usr/lib/pkgconfig/libnsl.pc exists in filesystem
python: /usr/bin/python exists in filesystem
Errors occurred, no packages were upgraded.
[root@NEEO-xxxxxxx neeo]# PIP
bash: PIP: command not found
[root@NEEO-xxxxxxx neeo]# pip install wheel
bash: pip: command not found

**Comment by iammoen** [comment]
What version of pacman do you have? You can check with this command: `pacman -V`

**Comment by iammoen** [comment]
Ok I found the issue, `python-pip` needs to be installed with the --force flag as well. This command should fix everything up for you: `sudo pacman -S --force python3 python-pip`
