### ISSUE TITLE
Invalid value path after installing ca-certificates

### ISSUE THREAD

**Issue by zynexiz** [jac459/NeeoDriversInBrain#3]
The instruction states that you should run 'sudo pacman -S --force ca-certificates'. The problem I ran into is that some pacman hooks returns invalid path, making further upgrades unavailable. Unfortunately this also meen that you can't upgrade pacman itself to fix is because of the hooks.

I have compiled pacman-static for armv7 to help fix this. You can find the binary in the link below. Just download it and place it in your neeo home folder. You might need to set the execute flag to with chmod +x pacman-static. Then run

`sudo ./pacman-static -S --overwrite '/*' pacman
`

This will upgrade pacman, and fixing the hooks along with it. You can then remove pacman-static,  you won't need it anymore. 

Link: [pacman-static binary](https://zoik.se/index.php/s/YR2yzEFGwdXtq9x).
sha256: 5ae7bc83f59ebd675e16272d0c842eeafae9c0839196c2bd08f9e0c637334493

NOTE: You will get the latest version of pacman where the force option has been removed, use **--overwrite '/*'** instead, it will do the same thing.

**Comment by tomdh76** [comment]
I also had invalid path issue and your pacman worked (no idea what pacman is used for but just following tutorial...;-) However when I got to
sudo pacman -S --force python3 python-pip
It got an error: error: invalid option '--force'
If I leave out --force I got another error:
error: failed to commit transaction (conflicting files)

Any suggestions?

**Comment by iammoen** [comment]
@zynexiz could you instead provide the instructions to do the compiling? Feels weird to have a binary downloaded from just some guy on the internet and then run with sudo. No offense.

**Comment by zynexiz** [comment]
Pacman is the package manager for Arch Linux (and other Arch based distros). The version on neeo is older, and --force is replaced with --overwrite, use --overwrite '/*' in replacement of force option.

[EDIT] The other message you are getting is because the files it tries to install already exists in the system, hence you will need to tell pacman to overwrite them.  It seems like neeo removed the database with installed packages in the official firmware.

**Comment by zynexiz** [comment]
@iammoen None taken :) You will need Arch Linux on an arm based system, like Raspberry Pi. Download the PKGBUILD from AUR (https://aur.archlinux.org/packages/pacman-static) and compile it with makepkg -si. It will take some time, think it took about 40-45 min. Then just copy the compiled binary to you brain (just need the pacman-static binary, you will find it in /bin).

**Comment by zynexiz** [comment]
After some tinkering, I found out that the first thing you _should_ do is installing pacman before any other packages. If you do this, you won't get invalid value path error. As stated in the guide, install ca-certificates, but also make sure you add pacman to the line.

`sudo pacman -S --force ca-certificates pacman`

@smarthomesydney You might want to add it to your guide? :)

Or, if you want to, you can install all missing [packages](https://github.com/jac459/NeeoDriversInBrain/files/5108528/packages.log) making sure you NEEO use the latest software packages available. I attached a list of what packages is installed in the brain. You can install them with

`sudo pacman -S --overwrite '/*' <package name(s)>`

After that, you can upgrade your system as a normal Arch Linux installation with

`sudo pacman -Syyu`

To free up some space after installing any packages with pacman, I recommended to clean the caches afterwards

`sudo pacman -Scc`

**Comment by smarthomesydney** [comment]
> A note.. The first thing you _should_ do is installing pacman before any other packages. If you do this, you won't get invalid value path error. As stated in the guide, install ca-certificates, but also make sure you add pacman to the line.
> 
> `sudo pacman -S --force ca-certificates pacman`
> 
> @smarthomesydney You might want to add it to your guide? :)

Are you recommending to force update Pacman CA certs after init install of Pacman? 
Also are you recommending this command be run along with the force update CA certs command or in place of it?

I got around the issue by deleting the hooks files that were causing the errors.  Any issues with deleting these files?

**Comment by zynexiz** [comment]
Deleting the hooks _might_ brake the system further down the line, I don't recommend it. You can install them both at the same time, just add pacman to the line and it will install latest pacman from the repo. [EDIT] I think you can replace ca-certificates with just pacman. Pacman depends on ca-certificates, and it will be installed along with it.

I found the list of what packages where installed in the brain from start, and have installed all of the packages now (added it to the comment). Just a note, after updating pacman, the --force option is invalid. It's replaced by --overwrite, --overwrite '/*' will accomplish the same thing.

**Comment by iammoen** [comment]
@zynexiz all good points. I just pushed some changes to the readme to reflect what you were saying.

**Comment by iammoen** [comment]
Going to close this as I believe the comments above have been addressed in the readme. If anyone believes that isn't true let me know! Thank you!
